# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 741e655cb2591933a1032271e0b354ce8e48fd4347584a32e51544f68a69118e90f741764defaa7b9a2c75e66c57a449563be918621aaaf99906c5c949cca692

test:
  secret_key_base: 0e91659b05adb373f8bfebb6c06fb67e6e3957491ad79f8f72e58b64b4d83beb9ece1a5012e4ec4ed7e914a948be83344eea00b7d02956b2f202a2dcce335b26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
